version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/webui"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
      - dependency-type: "production"
    auto-merge:
      enabled: true
      method: squash
